### PR TITLE
Critical section

### PR DESCRIPTION
**Pull request by hesic73**
试图对mutex做优化的结果。意义不是很大，但应该不会更慢。

### CODE REVIEW

**Comment by FanShupei** [comment]
Please remove build artifact, such as `*.o` and `*.d`

**Comment by hesic73** [comment]
sorry忘记了。刚刚冷静一下觉得这分支还是不merge比较好

**Comment by FanShupei** [comment]
As far as I know, `std::mutex` is backed by CriticalSection in Windows and backed by pthread_mutex in linux. It's basicly what you've done in critical_section.hpp.

**Comment by hesic73** [comment]
呜呜是的。。。

**Pull request closed without merging**
